context:
  version: 0.4.0

package:
  name: cherab-inversion
  version: ${{ version }}

source:
  url: https://github.com/munechika-koyo/cherab_inversion/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 92fa6dae87b6b54c2ec1b54baa287bd03254a97752b3a6adb9455f761974ebe6

build:
  number: 0
  noarch: python
  script:
    content: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatch-vcs
    - hatchling
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - scikit-sparse
    - rich

tests:
  - python:
      imports:
        - cherab.inversion
      pip_check: true
  - script:
      - pytest
    files:
      source:
        - tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest

about:
  summary: Cherab inversion framework
  description: Cherab add-on module that provides inversion techniques including SVD, MFR, and more.
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://cherab-inversion.readthedocs.io/en/stable/
  repository: https://github.com/munechika-koyo/cherab_inversion
  documentation: https://cherab-inversion.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - munechika-koyo
